### ISSUE TITLE
Memory Leak When Handling Error with a Single Argument

### ISSUE THREAD

**Issue by oprosvir** [byaliego/push_swap#9]
![Screenshot from 2024-03-28 01-38-40](https://github.com/ayogun/push_swap/assets/94167082/b1b68de0-fcbe-4090-b439-f080307d06a5)

![Screenshot from 2024-03-28 01-44-05](https://github.com/ayogun/push_swap/assets/94167082/edd43f9c-8c65-4587-bccc-4fcf2d24c3a9)
![Screenshot from 2024-03-28 01-45-29](https://github.com/ayogun/push_swap/assets/94167082/6dc12b7f-c391-4312-a400-e58f528b1d0f)

**Comment by ayogun** [comment]
Hey Olga, thank you for bringing it up. Although, the thing is there all kind of bad things happen in my code lol. The thing is, somehow I pushed the wrong "not working" code. I couldn't find the final working version. So, you can encounter all kind of errors. I just leave the code here for people to look at my approach. Please avoid to use it since it's error prone :(
